Repository kuzzleio/kuzzle-plugin-auth-passport-local, pull requests merged in 2020-05, with the labels that each got.

#70 Password policies
  .eslintrc.json
  .mocharc.yml
  README.md
  docker-compose.yml
  lib/_typedef.js
  lib/getUserConstructor.js
  lib/index.js
  manifest.json
  package-lock.json
  package.json
  test/create.test.js
  test/delete.test.js
  test/exists.test.js
  test/getById.test.js
  test/getInfo.test.js
  test/getResetPasswordTokenAction.test.js
  test/init.test.js
  test/mock/getUserRepository.mock.js
  test/mock/passwordManager.mock.js
  test/mock/pluginContext.mock.js
  test/mock/repository.mock.js
  test/resetPasswordAction.test.js
  test/update.test.js
  test/user.test.js
  test/validate.test.js
  test/verify.test.js
Labels: changelog:new-features

#72 Fix: get the current password from the request body instead of in querystrings
  README.md
  lib/index.js
  test/delete.test.js
  test/update.test.js
Labels: changelog:securities

#73 Release 6.2.0
  .eslintrc.json
  .mocharc.yml
  README.md
  docker-compose.yml
  lib/_typedef.js
  lib/getUserConstructor.js
  lib/index.js
  manifest.json
  package-lock.json
  package.json
  test/create.test.js
  test/delete.test.js
  test/exists.test.js
  test/getById.test.js
  test/getInfo.test.js
  test/getResetPasswordTokenAction.test.js
  test/init.test.js
  test/mock/getUserRepository.mock.js
  test/mock/passwordManager.mock.js
  test/mock/pluginContext.mock.js
  test/mock/repository.mock.js
  test/resetPasswordAction.test.js
  test/update.test.js
  test/user.test.js
  test/validate.test.js
  test/verify.test.js
Labels: release
